version: "3"

services:
  db:
    image: mysql
    container_name: db-mysql-dock
    restart: always
    ports:
      - 3307:3306
    env_file:
      - ./config/db.env
    volumes:
      - db:/var/lib/mysql

volumes:
  db: ~